<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>

    </style>
</head>

<body>
    <div style="text-align: center">
        <img src="{{asset(config('company_info.logo'))}}" alt="">
        <h1 style="margin:0; padding:0">Balance Sheet</h1>
        <strong>December 31,</strong>
    </div>
    <br>

    <div>
        <table>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    <table>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                        <tr>
                            <td>
                                sfsfsf
                            </td>
                            <td>
                                sfsfsf
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>

</body>

</html>
